server:
  port: 9000

#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sqltest?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #模板引擎配置
  thymeleaf:
    prefix: classpath:/templates/
    encoding: utf-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html

#mybatis  也可以用扫描绑定  mappper和mapper.xml @MapperScan("com.hand.*.mapper")
  #(扫描注意：要包结构一至，target里会把他俩合到一起，并且名字要一样)
#mybatis:
#  mapper-locations: classpath:mapper/*.xml #mapper映射文件路径
#  type-aliases-package: com/hand/springbootMybatis/entity  #映射实体类的路径包


